# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or find_or_create_byd alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Grade.find_or_create_by(name: '1a', grade_type: Grade.grade_types[:font], band: Grade.bands[:easy])
Grade.find_or_create_by(name: '1b', grade_type: Grade.grade_types[:font], band: Grade.bands[:easy])
Grade.find_or_create_by(name: '1c', grade_type: Grade.grade_types[:font], band: Grade.bands[:easy])
Grade.find_or_create_by(name: '2a', grade_type: Grade.grade_types[:font], band: Grade.bands[:easy])
Grade.find_or_create_by(name: '2b', grade_type: Grade.grade_types[:font], band: Grade.bands[:easy])
Grade.find_or_create_by(name: '2c', grade_type: Grade.grade_types[:font], band: Grade.bands[:easy])
Grade.find_or_create_by(name: '3a', grade_type: Grade.grade_types[:font], band: Grade.bands[:easy])
Grade.find_or_create_by(name: '3b', grade_type: Grade.grade_types[:font], band: Grade.bands[:easy])
Grade.find_or_create_by(name: '3c', grade_type: Grade.grade_types[:font], band: Grade.bands[:easy])
Grade.find_or_create_by(name: '4a', grade_type: Grade.grade_types[:font], band: Grade.bands[:easy])
Grade.find_or_create_by(name: '4b', grade_type: Grade.grade_types[:font], band: Grade.bands[:easy])
Grade.find_or_create_by(name: '4c', grade_type: Grade.grade_types[:font], band: Grade.bands[:easy])
Grade.find_or_create_by(name: '5a', grade_type: Grade.grade_types[:font], band: Grade.bands[:moderate])
Grade.find_or_create_by(name: '5b', grade_type: Grade.grade_types[:font], band: Grade.bands[:moderate])
Grade.find_or_create_by(name: '5c', grade_type: Grade.grade_types[:font], band: Grade.bands[:moderate])
Grade.find_or_create_by(name: '6a', grade_type: Grade.grade_types[:font], band: Grade.bands[:intermediate])
Grade.find_or_create_by(name: '6a+', grade_type: Grade.grade_types[:font], band: Grade.bands[:intermediate])
Grade.find_or_create_by(name: '6b', grade_type: Grade.grade_types[:font], band: Grade.bands[:intermediate])
Grade.find_or_create_by(name: '6b+', grade_type: Grade.grade_types[:font], band: Grade.bands[:intermediate])
Grade.find_or_create_by(name: '6c', grade_type: Grade.grade_types[:font], band: Grade.bands[:intermediate])
Grade.find_or_create_by(name: '6c+', grade_type: Grade.grade_types[:font], band: Grade.bands[:intermediate])
Grade.find_or_create_by(name: '7a', grade_type: Grade.grade_types[:font], band: Grade.bands[:advanced])
Grade.find_or_create_by(name: '7a+', grade_type: Grade.grade_types[:font], band: Grade.bands[:advanced])
Grade.find_or_create_by(name: '7b', grade_type: Grade.grade_types[:font], band: Grade.bands[:advanced])
Grade.find_or_create_by(name: '7b+', grade_type: Grade.grade_types[:font], band: Grade.bands[:advanced])
Grade.find_or_create_by(name: '7c', grade_type: Grade.grade_types[:font], band: Grade.bands[:advanced])
Grade.find_or_create_by(name: '7c+', grade_type: Grade.grade_types[:font], band: Grade.bands[:advanced])
Grade.find_or_create_by(name: '8a', grade_type: Grade.grade_types[:font], band: Grade.bands[:expert])
Grade.find_or_create_by(name: '8a+', grade_type: Grade.grade_types[:font], band: Grade.bands[:expert])
Grade.find_or_create_by(name: '8b', grade_type: Grade.grade_types[:font], band: Grade.bands[:expert])
Grade.find_or_create_by(name: '8b+', grade_type: Grade.grade_types[:font], band: Grade.bands[:expert])
Grade.find_or_create_by(name: '8c', grade_type: Grade.grade_types[:font], band: Grade.bands[:expert])
Grade.find_or_create_by(name: '8c+', grade_type: Grade.grade_types[:font], band: Grade.bands[:expert])
Grade.find_or_create_by(name: '9a', grade_type: Grade.grade_types[:font], band: Grade.bands[:expert])
Grade.find_or_create_by(name: '9a+', grade_type: Grade.grade_types[:font], band: Grade.bands[:expert])
Grade.find_or_create_by(name: '9b', grade_type: Grade.grade_types[:font], band: Grade.bands[:expert])
